/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ikwattro.egrid;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8940735017984238031L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceEvent\",\"namespace\":\"com.ikwattro.egrid\",\"fields\":[{\"name\":\"device_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"charging_source\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"current_capacity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceEvent> ENCODER =
      new BinaryMessageEncoder<DeviceEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceEvent> DECODER =
      new BinaryMessageDecoder<DeviceEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeviceEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String device_id;
  private java.lang.String charging_source;
  private int current_capacity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceEvent() {}

  /**
   * All-args constructor.
   * @param device_id The new value for device_id
   * @param charging_source The new value for charging_source
   * @param current_capacity The new value for current_capacity
   */
  public DeviceEvent(java.lang.String device_id, java.lang.String charging_source, java.lang.Integer current_capacity) {
    this.device_id = device_id;
    this.charging_source = charging_source;
    this.current_capacity = current_capacity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return device_id;
    case 1: return charging_source;
    case 2: return current_capacity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: device_id = value$ != null ? value$.toString() : null; break;
    case 1: charging_source = value$ != null ? value$.toString() : null; break;
    case 2: current_capacity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'device_id' field.
   * @return The value of the 'device_id' field.
   */
  public java.lang.String getDeviceId() {
    return device_id;
  }


  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'charging_source' field.
   * @return The value of the 'charging_source' field.
   */
  public java.lang.String getChargingSource() {
    return charging_source;
  }


  /**
   * Sets the value of the 'charging_source' field.
   * @param value the value to set.
   */
  public void setChargingSource(java.lang.String value) {
    this.charging_source = value;
  }

  /**
   * Gets the value of the 'current_capacity' field.
   * @return The value of the 'current_capacity' field.
   */
  public int getCurrentCapacity() {
    return current_capacity;
  }


  /**
   * Sets the value of the 'current_capacity' field.
   * @param value the value to set.
   */
  public void setCurrentCapacity(int value) {
    this.current_capacity = value;
  }

  /**
   * Creates a new DeviceEvent RecordBuilder.
   * @return A new DeviceEvent RecordBuilder
   */
  public static com.ikwattro.egrid.DeviceEvent.Builder newBuilder() {
    return new com.ikwattro.egrid.DeviceEvent.Builder();
  }

  /**
   * Creates a new DeviceEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceEvent RecordBuilder
   */
  public static com.ikwattro.egrid.DeviceEvent.Builder newBuilder(com.ikwattro.egrid.DeviceEvent.Builder other) {
    if (other == null) {
      return new com.ikwattro.egrid.DeviceEvent.Builder();
    } else {
      return new com.ikwattro.egrid.DeviceEvent.Builder(other);
    }
  }

  /**
   * Creates a new DeviceEvent RecordBuilder by copying an existing DeviceEvent instance.
   * @param other The existing instance to copy.
   * @return A new DeviceEvent RecordBuilder
   */
  public static com.ikwattro.egrid.DeviceEvent.Builder newBuilder(com.ikwattro.egrid.DeviceEvent other) {
    if (other == null) {
      return new com.ikwattro.egrid.DeviceEvent.Builder();
    } else {
      return new com.ikwattro.egrid.DeviceEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceEvent>
    implements org.apache.avro.data.RecordBuilder<DeviceEvent> {

    private java.lang.String device_id;
    private java.lang.String charging_source;
    private int current_capacity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ikwattro.egrid.DeviceEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.charging_source)) {
        this.charging_source = data().deepCopy(fields()[1].schema(), other.charging_source);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.current_capacity)) {
        this.current_capacity = data().deepCopy(fields()[2].schema(), other.current_capacity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ikwattro.egrid.DeviceEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.charging_source)) {
        this.charging_source = data().deepCopy(fields()[1].schema(), other.charging_source);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.current_capacity)) {
        this.current_capacity = data().deepCopy(fields()[2].schema(), other.current_capacity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'device_id' field.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return device_id;
    }


    /**
      * Sets the value of the 'device_id' field.
      * @param value The value of 'device_id'.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder setDeviceId(java.lang.String value) {
      validate(fields()[0], value);
      this.device_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'device_id' field has been set.
      * @return True if the 'device_id' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'device_id' field.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'charging_source' field.
      * @return The value.
      */
    public java.lang.String getChargingSource() {
      return charging_source;
    }


    /**
      * Sets the value of the 'charging_source' field.
      * @param value The value of 'charging_source'.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder setChargingSource(java.lang.String value) {
      validate(fields()[1], value);
      this.charging_source = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'charging_source' field has been set.
      * @return True if the 'charging_source' field has been set, false otherwise.
      */
    public boolean hasChargingSource() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'charging_source' field.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder clearChargingSource() {
      charging_source = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'current_capacity' field.
      * @return The value.
      */
    public int getCurrentCapacity() {
      return current_capacity;
    }


    /**
      * Sets the value of the 'current_capacity' field.
      * @param value The value of 'current_capacity'.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder setCurrentCapacity(int value) {
      validate(fields()[2], value);
      this.current_capacity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'current_capacity' field has been set.
      * @return True if the 'current_capacity' field has been set, false otherwise.
      */
    public boolean hasCurrentCapacity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'current_capacity' field.
      * @return This builder.
      */
    public com.ikwattro.egrid.DeviceEvent.Builder clearCurrentCapacity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceEvent build() {
      try {
        DeviceEvent record = new DeviceEvent();
        record.device_id = fieldSetFlags()[0] ? this.device_id : (java.lang.String) defaultValue(fields()[0]);
        record.charging_source = fieldSetFlags()[1] ? this.charging_source : (java.lang.String) defaultValue(fields()[1]);
        record.current_capacity = fieldSetFlags()[2] ? this.current_capacity : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceEvent>
    READER$ = (org.apache.avro.io.DatumReader<DeviceEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.device_id);

    out.writeString(this.charging_source);

    out.writeInt(this.current_capacity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.device_id = in.readString();

      this.charging_source = in.readString();

      this.current_capacity = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.device_id = in.readString();
          break;

        case 1:
          this.charging_source = in.readString();
          break;

        case 2:
          this.current_capacity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










